export const FEATURE_LIST_SUCCESS = "FEATURE_LIST_SUCCESS";
export const FEATURE_LIST_REQUEST = "FEATURE_LIST_REQUEST";
export const FEATURE_LIST_FAIL = "FEATURE_LIST_FAIL";

export const FEATURE_PROPERTY_SUCCESS = "FEATURE_PROPERTY_SUCCESS";
export const FEATURE_PROPERTY_REQUEST = "FEATURE_PROPERTY_REQUEST";
export const FEATURE_PROPERTY_FAIL = "FEATURE_PROPERTY_FAIL";

export const SEARCH_ITEM_SUCCESS = "SEARCH_ITEM_SUCCESS";
export const SEARCH_ITEM_REQUEST = "SEARCH_ITEM_REQUEST";
export const SEARCH_ITEM_FAIL = "SEARCH_ITEM_FAIL";
